language: python
python:
    - "3.9"
    - "3.11"

install:
    - pip install yt-dlp > /dev/null

before_script:
    - printenv
    - ls -l
    - pip install wheel
    - python setup.py sdist bdist_wheel
    - python setup.py install

sudo: false
